sudo: required
services:
  - docker
  #- redis-server

before_install:
  #- docker-compose -f docker-compose-dev.yml up -d --build
  #- docker exec -it official-finders-server-test bash
  - docker run -d --name redisDev -p 6379:6379 redis
  - docker build -t datdevboi/official-finders-server -f Dockerfile.dev .

# before_script: sudo redis-server /etc/redis/redis.confg --port 6379

script:
  #- docker container ls
  #- docker exec -it official-finders-server-test bash
  #- docker run officialfindersserver_server npm run test -- --detectOpenHandles --coverage
  #- docker run -e REDIS_PORT=6379 -e REDIS_HOST=redis datdevboi/official-finders-server npm run start
  - docker run -e REDIS_PORT=6379 -e REDIS_HOST="localhost" datdevboi/official-finders-server npm run test:ci --detectOpenHandles --coverage

after_success:
  - ./build-docker-push.sh