sudo: required
services:
  - docker
  - redis-server

before_install:
  - docker-compose -f docker-compose-dev.yml up -d --build
  # - docker build -t datdevboi/official-finders-server -f Dockerfile.dev .

script:
  - docker exec -it official-finders-server-test sh && npm run test -- --coverage
  # - docker run datdevboi/official-finders-server npm run test -- --coverage
