sudo: required
services:
  - docker
  - redis-server

before_install:
  - docker build -t datdevboi/official-finders-server -f Dockerfile.dev .

script:
  - docker run datdevboi/official-finders-server npm run test -- --coverage
