version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=official-finders-db-prod
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tj@officialfinders.com
      PGADMIN_DEFAULT_PASSWORD: Richard123!
    restart: unless-stopped     
  redis:
    image: redis
    expose:
      - 6379
  server:
    image: officialfinders/official-finders-server-prod:latest
    ports:
      - 80:3000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PGHOST=db
      - PGDATABASE=official-finders-db-prod
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGPORT=5432
    restart: 'always'  
    container_name: official-finders-server
    depends_on:
      - db
      - redis
    command: ["./wait-for-it.sh", "db:5432", "-t", "4",  "--", "node", "build/index.js"]  
  
