version: "3"
services:
  db:
    image: postgres
  redis:
    image: redis
    expose:
      - 6379
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - redis
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
