version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=official-finders-server-dev

  redis:
    image: redis
    expose:
      - 6379
  server:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PGHOST=db
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGPORT=5432
    container_name: official-finders-server
    # volumes:
    #   - /app/node_modules
    #   - .:/app
    depends_on:
      - redis
      - db
    #command: ["./wait-for-it.sh", "db:5432", "--", "node", "build/src/index.js"]   
    #command: ["npm", "run", "start:dev"]  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: official-finders-server-test
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
