version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=official-finders-server-dev
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped 
  redis:
    image: redis
    expose:
      - 6379
  server:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PGHOST=postgres
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGPORT=5432
    container_name: official-finders-server
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - redis
      - postgres
    #command: ["./wait-for-it.sh", "db:5432", "--", "node", "build/src/index.js"]   
    #command: ["npm", "run", "start:dev"]  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: official-finders-server-test
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
